import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/usr/bin/chromium-browser' });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
await p.goto('http://localhost:4321/ares_materials_estudi/javascript/canvas-drawing/', { waitUntil: 'networkidle' });
const run = p.locator('live-code [data-run]').first();
const reset = p.locator('live-code [data-reset]').first();
const [a, c] = [await run.boundingBox(), await reset.boundingBox()];
console.log('Run  y:', a.y.toFixed(1), 'h:', a.height.toFixed(1));
console.log('Reset y:', c.y.toFixed(1), 'h:', c.height.toFixed(1));
console.log(Math.abs(a.y - c.y) < 0.5 ? 'ALIGNED' : 'STILL OFFSET by ' + Math.abs(a.y - c.y).toFixed(1) + 'px');
await p.locator('.live-actions').first().scrollIntoViewIfNeeded();
await p.waitForTimeout(600);
await p.locator('live-code').first().screenshot({ path: '/home/massagno/.claude/jobs/b9bcc5ff/tmp/buttons.png' });
await b.close();
